time_format_default = "Jan 2, 2006"

# SEO keywords and description for site
keywords = "cv, resume, personal, blog, homepage"
subtitle = "Personal blog and homepage of Dzmitry Hramyka"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

[header]
  # logo = "logo.svg"
  logo = "photo.png"

[footer]
  since = 2024
  poweredby = false
  
[social_media]

  [[social_media.items]]
    enabled = true
    title = 'Twitter'
    icon = 'brand-x'
    link = 'https://twitter.com/grom_dimon/'

  [[social_media.items]]
    enabled = true
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/in/gromdimon/'

  [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/gromdimon'