time_format_default = "Jan 2, 2006"

# SEO keywords and description for site
keywords = "cv"
subtitle = "CV"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

[header]
  logo = "photo.png"

[footer]
  since = 2024
  poweredby = false
